name: bgs_control
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.2+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.8
  get_it: ^7.7.0
  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.2.2
  uuid: ^4.4.2
  flutter_text_viewer: ^0.0.6
  share_plus: ^10.0.2
  package_info_plus: ^8.1.3
  flutter_native_splash: ^2.3.10
  wheel_picker: ^0.2.1
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
#  workmanager:
#    git:
#      url: https://github.com/absar/flutter_workmanager.git
#      ref: ios-bg-tasks-enh-final

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^3.0.0
  rename: ^3.0.2

flutter:
  uses-material-design: true

  assets:
     - images/invitation.png
     - images/select_method.png
     - images/program_params.png
     - images/device.png
     - images/connect_to_device.png
     - images/background_woman.png
     - images/connect_device.png
     - images/connected_device.png
     - images/attention.png
     - images/background_hand.png
     - images/play.png
     - images/pause.png
     - images/stop.png
     - images/sk_member.png
     - images/sk_member_splash.png
     - images/texel_200_light.png
     - images/texel_splash.png
     - images/texel_200.png
     - lib/assets/icons/device_menu.png
     - lib/assets/icons/methods_menu.png
     - lib/assets/icons/bluetooth.png

     - lib/assets/programs/prg_main.json
     - lib/assets/programs/select_prg.json
     - lib/assets/icons/programs/togo.png
     - lib/assets/icons/programs/ankle_pain.png
     - lib/assets/icons/programs/elbow_pain.png
     - lib/assets/icons/programs/healing_massage_joints.png
     - lib/assets/icons/programs/healing_massage_joints_active.png
     - lib/assets/icons/programs/healing_massage_muscles_active.png
     - lib/assets/icons/programs/hip_pain.png
     - lib/assets/icons/programs/joints_discomfort_1.png
     - lib/assets/icons/programs/joints_discomfort_2.png
     - lib/assets/icons/programs/knee_pain.png
     - lib/assets/icons/programs/lower_back_pain.png
     - lib/assets/icons/programs/muscles_longterm_voltage_1.png
     - lib/assets/icons/programs/muscles_longterm_voltage_2.png
     - lib/assets/icons/programs/muscles_sharp_voltage_1.png
     - lib/assets/icons/programs/muscles_sharp_voltage_2.png
     - lib/assets/icons/programs/phantom_pain_amputated_limb.png
     - lib/assets/icons/programs/phantom_pains_lower_limb.png
     - lib/assets/icons/programs/relaxing_massage_joints.png
     - lib/assets/icons/programs/relaxing_massage_joints_active.png
     - lib/assets/icons/programs/relaxing_massage_muscles_active.png
     - lib/assets/icons/programs/relaxing_muscle_massage.png
     - lib/assets/icons/programs/revitalizing_muscle_massage.png
     - lib/assets/icons/programs/shoulder_pain.png
     - lib/assets/icons/programs/sport_joints_relaxation.png
     - lib/assets/icons/programs/sport_joints_warmup.png
     - lib/assets/icons/programs/sport_joints_workout.png
     - lib/assets/icons/programs/sport_joints.png
     - lib/assets/icons/programs/sport_muscles_relaxation.png
     - lib/assets/icons/programs/sport_muscles_warmup.png
     - lib/assets/icons/programs/sport_muscles_workout.png
     - lib/assets/icons/programs/sport_muscles.png
     - lib/assets/icons/programs/tunnel_syndrome.png
     - lib/assets/icons/programs/tunnel_syndrome_almost_round.png
     - lib/assets/icons/programs/tunnel_syndrome_round.png
     - lib/assets/icons/programs/tunnel_syndrome_round.psd
     - lib/assets/icons/program_menu/01_discomfort.png
     - lib/assets/icons/program_menu/02_fitness.png
     - lib/assets/icons/program_menu/03_massage.png
     - lib/assets/icons/program_menu/04_sport.png
     - lib/assets/icons/program_menu/05_easy.png
     - lib/assets/icons/program_menu/06_hard.png
     - lib/assets/icons/program_menu/07_recent.png
     - lib/assets/icons/program_menu/08_longTime.png
     - lib/assets/icons/program_menu/09_back.png
     - lib/assets/icons/program_menu/10_knees.png

     - lib/assets/bgs/BGS_128.png
     - lib/assets/bgs/BGS_128_c.png
     - lib/assets/bgs/BGS_256.png
     - lib/assets/bgs/BGS_32.png
     - lib/assets/bgs/BGS_64.png

flutter_native_splash:
  color: "#FFFFFF"
  image: "images/texel_splash.png"
  branding: "images/sk_member_splash.png"
  branding_mode: bottom
  branding_bottom_padding: 24
  android_12:
   image: "images/texel_splash.png"
   branding: "images/sk_member_splash.png"